### ISSUE TITLE
Could you export gerber?

### ISSUE THREAD

**Issue by DRCRecoveryData** [cbwhickstein/Flipper_Zero_DIY#1]
Hi,

Have you made pcb? could you upload some image and gerber file to order on jlcpcb?

**Comment by cbwhickstein** [comment]
Hey sorry, since this project isn't complete yet there are no gerber files to export. If I ever finish this project, I will post it on r/flipperzero to update everyone.

**Comment by DRCRecoveryData** [comment]
> Hey sorry, since this project isn't complete yet there are no gerber files to export. If I ever finish this project, I will post it on r/flipperzero to update everyone.

Could you share how to upload firmware on new chip?

**Comment by cbwhickstein** [comment]
As I don't own a flipper zero, I can not provide further assistance in that matter. I would recommend to search for that on the official flipper zero website or on the r/flipperzero. But please just search for it and don't create another post. It has been asked like a million times.
